#!/usr/bin/env bash
# Bash script that displays information about subdomains.

function get_record_type() {
  local output=$(dig $1.$2 | grep -A1 'ANSWER SECTION:')
  if echo "$output" | grep -q 'CNAME'; then
    echo "CNAME"
  else
    echo "A"
  fi
}

function get_destination() {
  local output=$(dig $1.$2 | grep -A1 'ANSWER SECTION:')
  local ip=$(echo "$output" | grep 'IN A ' | awk '{print $5}')
  if [ -z "$ip" ]; then
    local cname=$(echo "$output" | grep 'IN CNAME ' | awk '{print $5}')
    echo "$cname"
  else
    echo "$ip"
  fi
}

if [ $# -eq 1 ]; then
  domain=$1
  subdomains=(www lb-01 web-01 web-02)
else
  domain=$1
  subdomains=($2)
fi

for subdomain in "${subdomains[@]}"
do
  record_type=$(get_record_type $subdomain $domain)
  destination=$(get_destination $subdomain $domain)
  echo "The subdomain $subdomain is a $record_type record and points to $destination"
done
