#!/usr/bin/env bash
# Bash script that displays information about subdomains.

# function get_record_type() {
#   local output=$(dig $1.$2 | grep -A1 'ANSWER SECTION:')
#   if echo "$output" | grep -q 'CNAME'; then
#     echo "CNAME"
#   else
#     echo "A"
#   fi
# }

# function get_destination() {
#   local output=$(dig $1.$2 | grep -A1 'ANSWER SECTION:')
#   local ip=$(echo "$output" | grep 'IN A ' | awk '{print $5}')
#   if [ -z "$ip" ]; then
#     local cname=$(echo "$output" | grep 'IN CNAME ' | awk '{print $5}')
#     echo "$cname"
#   else
#     echo "$ip"
#   fi
# }

# if [ $# -eq 1 ]; then
#   domain=$1
#   subdomains=(www lb-01 web-01 web-02)
# else
#   domain=$1
#   subdomains=($2)
# fi

# for subdomain in "${subdomains[@]}"
# do
#   record_type=$(get_record_type $subdomain $domain)
#   destination=$(get_destination $subdomain $domain)
#   echo "The subdomain $subdomain is a $record_type record and points to $destination"
# done

# rewritten code so that it shows IP

if [ $# -eq 0 ]; then
  echo "Usage: $0 domain [subdomain]"
  exit 1
fi

domain=$1
subdomain=${2:-"www lb-01 web-01 web-02"}

function get_record_type() {
  local output=$(dig $1.$2 | grep -A1 'ANSWER SECTION:')
  if echo "$output" | grep -q 'CNAME'; then
    echo "CNAME"
  else
    echo "A"
  fi
}

for s in $subdomain; do
  dest=$(dig +short $s.$domain | awk '{print $1}')
#   record=$(dig +short $s.$domain | awk '{print $4}')
  record=$(get_record_type $subdomain $domain)
  echo "The subdomain $s is a $record record and points to $dest"
done
