#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a
# GET request (requesting a page) using curl,
# it must return a page that contains the string Hello World!

sudo apt-get update -y
sudo apt-get install nginx -y

# Allow nginx on firewall
ufw allow 'Nginx HTTP'

# create new index
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

# start nginx
service nginx start
